import { Montserrat, Roboto } from "next/font/google";
import "@/styles/globals.css";

const montserrat = Montserrat({
  weigth: ["700", "900"],
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Shivam Rai | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
